In [2]:
import joblib
import pandas as pd
import numpy as np
import polars as pl

import yfinance as yf

import akshare as ak

In [3]:
import sys
sys.path.append('./Code')

In [4]:
sys.path.append('/home/jun23/workspace/GitHub/kzz')

In [5]:
from mytools.util import unset_proxy
from data_center import DataCenter

In [6]:
dc = DataCenter()

In [7]:
from YahooOHLCFetcher import get_adjusted_ohlc

In [55]:
olhc_data = joblib.load('./Data/sp500_ohlc_data.pkl')

In [76]:
failed_tickers = []
for ticker, df in olhc_data.items():
    tmp = df.loc[~df['close'].isna()]
    if len(tmp) == 0:
        failed_tickers.append(ticker)

In [77]:
len(failed_tickers)

150

In [78]:
failed_tickers

['ANSS',
 'BRK.B',
 'BF.B',
 'DFS',
 'HES',
 'JNPR',
 'PARA',
 'WBA',
 'GPS',
 'KSU',
 'MXIM',
 'ALXN',
 'HFC',
 'FLIR',
 'VAR',
 'CXO',
 'TIF',
 'NBL',
 'ETFC',
 'ADS',
 'JWN',
 'AGN',
 'RTN',
 'ARNC',
 'XEC',
 'WCG',
 'VIAB',
 'CELG',
 'TSS',
 'APC',
 'RHT',
 'LLL',
 'DWDP',
 'SRCL',
 'XL',
 'GGP',
 'DPS',
 'MON',
 'WYN',
 'PDCO',
 'CHK',
 'SNI',
 'BCR',
 'LVLT',
 'SPLS',
 'WFM',
 'MNK',
 'RAI',
 'YHOO',
 'MJN',
 'DNB',
 'SWN',
 'FTR',
 'LLTC',
 'ENDP',
 'STJ',
 'LM',
 'DO',
 'TYC',
 'CPGX',
 'CVC',
 'BXLT',
 'ARG',
 'TWC',
 'ESV',
 'GMCR',
 'BRCM',
 'ALTR',
 'CMCSK',
 'CSC',
 'SIAL',
 'HCBK',
 'JOY',
 'HSP',
 'PLL',
 'DTV',
 'FDO',
 'KRFT',
 'QEP',
 'LO',
 'WIN',
 'DNR',
 'AVP',
 'CFN',
 'SWY',
 'RDC',
 'X',
 'FRX',
 'IGT',
 'LSI',
 'WPX',
 'LIFE',
 'JDSU',
 'JCP',
 'NYX',
 'SAI',
 'APOL',
 'DF',
 'BIG',
 'FII',
 'RRD',
 'KFT',
 'LXK',
 'PGN',
 'NVLS',
 'AKS',
 'MWW',
 'JNS',
 'CEPH',
 'NOVL',
 'GENZ',
 'MDP',
 'EK',
 'MIL',
 'STR',
 'XTO',
 'BJS',
 'CTX',
 'ACAS',
 'LEH',
 'FRE',
 'FNM',
 'DJ',
 'AV',
 'NCR',
 'FDC',
 'TSG',
 'QTRN',
 'BS',
 'GRA',
 'RAD',
 'SMS',
 'LDW',
 'HPH',
 'CTLT',
 'MRO',
 'PXD',
 'ATVI',
 'DISH',
 'FRC',
 'SIVB',
 'ABMD',
 'FBHS',
 'TWTR',
 'NLSN',
 'CTXS',
 'DRE',
 'CERN',
 'PBCT',
 'XLNX']

In [66]:
start_date, end_date = '1995-01-01', '2025-10-31'
interval = '1d'

In [81]:
data, failed = get_adjusted_ohlc(
    tickers=['TWTR'],
    start_date=start_date,
    end_date=end_date,
    interval=interval
)

/home/jun23/workspace/GitHub/Cross-Sectional-Momentum-LTR/Code/YahooOHLCFetcher.py:76: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(

1 Failed download:
['TWTR']: YFTzMissingError('possibly delisted; no timezone found')

Starting download for 1 tickers in 1 batches
Date range: 1995-01-01 to 2025-10-31
============================================================

Batch 1/1: Processing 1 tickers (0 remaining)
--------------------------------------------------
Downloading data for: TWTR
✗ Failed to process TWTR: Empty DataFrame for TWTR

============================================================
Download Summary:
Successfully processed: 0/1 tickers
Failed tickers: ['TWTR']

# 如何获取已经退市的美股历史价格数据

## 1. yfinance

不行

In [83]:
data = yf.download(
    tickers=['TWTR'],
    start=start_date,
    end='2022-10-27',
    interval=interval,
    group_by='ticker',
    progress=False,
    threads=False,
    auto_adjust=False,
)

1 Failed download:
['TWTR']: YFTzMissingError('possibly delisted; no timezone found')

In [36]:

try:
    twtr = yf.Ticker("TWTR")
    # 明确指定获取退市前的历史数据
    hist_data = twtr.history(start="2021-01-01", end="2021-10-28")
    if hist_data.empty:
        print("未获取到数据。")
    else:
        print(hist_data.tail())
except Exception as e:
    print(f"获取数据时出现错误: {e}")

$TWTR: possibly delisted; no timezone found

未获取到数据。

## 2. Akshare

- 免费
- 按symbol查询，不能按日期

In [10]:
us_symbols = pl.DataFrame(dc.db.us_symbol.find({}, {'_id': 0}))

In [11]:
us_symbols

shape: (16_415, 3)
┌─────────────────────────────┬─────────────────────────────┬────────┐
│ name                        ┆ cname                       ┆ symbol │
│ ---                         ┆ ---                         ┆ ---    │
│ str                         ┆ str                         ┆ str    │
╞═════════════════════════════╪═════════════════════════════╪════════╡
│ NVIDIA Corp.                ┆ 英伟达公司                  ┆ NVDA   │
│ Apple, Inc.                 ┆ 苹果公司                    ┆ AAPL   │
│ Microsoft Corp.             ┆ 微软公司                    ┆ MSFT   │
│ Alphabet, Inc.              ┆ 谷歌                        ┆ GOOG   │
│ Alphabet, Inc.              ┆ 谷歌A类股                   ┆ GOOGL  │
│ …                           ┆ …                           ┆ …      │
│ Zura Bio Ltd.               ┆ Zura Bio Ltd.               ┆ ZURAW  │
│ Volatility Premium Plus ETF ┆ Volatility Premium Plus ETF ┆ ZVOL   │
│ ZyVersa Therapeutics, Inc.  ┆ ZyVersa Therapeutics, Inc.  ┆ ZVSAW  │
│ IEX Test symbol             ┆ IEX Test symbol             ┆ ZXIET  │
│ ZYN                         ┆ ZYN                         ┆ ZYN    │
└─────────────────────────────┴─────────────────────────────┴────────┘

In [12]:
def _ak_update_us_daily(dc, symbol):
    try:
        df = ak.stock_us_daily(symbol=symbol, adjust="")
        if len(df) == 0:
            print(f'not data for {symbol}')
            return False
        df['symbol'] = symbol
        res = dc.db.ak_us_daily.insert_many(df.to_dict('records'))
        if not res.acknowledged:
            print(f'insert to db failed, symbol={symbol}')
            return False
        return True
    except Exception as ex:
        print(f'_ak_update_us_daily throw ex: {ex}, symbol = {symbol}')
        return False

def _ak_update_us_qfq_factor(dc, symbol):
    try:
        df = ak.stock_us_daily(symbol=symbol, adjust="qfq-factor")
        if len(df) == 0:
            print(f'_ak_update_us_qfq_factor: not data for {symbol}')
            return False
        df['symbol'] = symbol
        df['qfq_factor'] = df['qfq_factor'].astype(np.float64)
        df['adjust'] = df['adjust'].astype(np.float64)
        res = dc.db.ak_us_daily_qfq_factor.insert_many(df.to_dict('records'))
        if not res.acknowledged:
            print(f'insert to db failed, symbol={symbol}')
            return False
        return True
    except Exception as ex:
        print(f'_ak_update_us_qfq_factor throw ex: {ex}, symbol = {symbol}')
        return False

In [13]:
from tqdm import tqdm

In [14]:
all_symbols = us_symbols['symbol']

In [15]:
ok = set(dc.db.ak_us_daily.distinct(key='symbol'))

In [16]:
failed_us_daily = []
failed_us_daily_qfq_factor = []

In [17]:
for symbol in tqdm(all_symbols):
    if symbol in ok:
        continue
    ret = _ak_update_us_daily(dc, symbol)
    if not ret:
        failed_us_daily.append(symbol)
        continue
    ok.add(symbol)
    ret = _ak_update_us_qfq_factor(dc, symbol)
    if not ret:
        failed_us_daily_qfq_factor.append(symbol)
    # break

 11%|████████████▏                                                                                                     | 1761/16415 [00:00<00:02, 5461.78it/s]

_ak_update_us_daily throw ex: list index out of range, symbol = EMBJ
_ak_update_us_daily throw ex: 'date', symbol = NCR
_ak_update_us_daily throw ex: 'date', symbol = AVG
_ak_update_us_daily throw ex: list index out of range, symbol = CEPV
_ak_update_us_daily throw ex: 'date', symbol = PAII.U
_ak_update_us_daily throw ex: 'date', symbol = SUNH
_ak_update_us_daily throw ex: 'date', symbol = SNLN
_ak_update_us_daily throw ex: 'date', symbol = VSAI

 39%|████████████████████████████████████████████▎                                                                    | 6429/16415 [00:00<00:00, 18618.07it/s]

_ak_update_us_daily throw ex: 'date', symbol = NYX
_ak_update_us_daily throw ex: 'date', symbol = BMAQU
_ak_update_us_daily throw ex: 'date', symbol = OTMO

 52%|███████████████████████████████████████████████████████████▍                                                      | 8565/16415 [00:01<00:01, 7039.84it/s]

_ak_update_us_daily throw ex: 'date', symbol = MULG
_ak_update_us_daily throw ex: 'date', symbol = VBLT
_ak_update_us_daily throw ex: 'date', symbol = ZEV
_ak_update_us_daily throw ex: 'date', symbol = CUBT
_ak_update_us_daily throw ex: 'date', symbol = HLEO

 61%|█████████████████████████████████████████████████████████████████████▎                                            | 9986/16415 [00:04<00:04, 1582.50it/s]

_ak_update_us_daily throw ex: 'date', symbol = CRTG
_ak_update_us_daily throw ex: 'date', symbol = ALN
_ak_update_us_daily throw ex: 'date', symbol = ATHX
_ak_update_us_daily throw ex: 'date', symbol = ELYS
_ak_update_us_daily throw ex: 'date', symbol = QSAM
_ak_update_us_daily throw ex: 'date', symbol = ELOX
_ak_update_us_daily throw ex: 'date', symbol = 2022-12-09
_ak_update_us_daily throw ex: 'date', symbol = AACT.U
_ak_update_us_daily throw ex: 'date', symbol = AAS
_ak_update_us_daily throw ex: 'date', symbol = ACONU
_ak_update_us_daily throw ex: 'date', symbol = AIGO
_ak_update_us_daily throw ex: 'date', symbol = ALEH
_ak_update_us_daily throw ex: 'date', symbol = ALOHA
_ak_update_us_daily throw ex: 'date', symbol = ALPX
_ak_update_us_daily throw ex: 'date', symbol = AMDI
_ak_update_us_daily throw ex: 'date', symbol = AMGSU

 66%|███████████████████████████████████████████████████████████████████████████▊                                      | 10912/16415 [00:08<00:07, 758.06it/s]

_ak_update_us_daily throw ex: 'date', symbol = ATEST.Z
_ak_update_us_daily throw ex: 'date', symbol = BFAI
_ak_update_us_daily throw ex: 'date', symbol = BLVE
_ak_update_us_daily throw ex: 'date', symbol = BRSHU
_ak_update_us_daily throw ex: 'date', symbol = BRTH
_ak_update_us_daily throw ex: 'date', symbol = BTRU

 70%|████████████████████████████████████████████████████████████████████████████████                                  | 11531/16415 [00:09<00:07, 676.34it/s]

_ak_update_us_daily throw ex: 'date', symbol = CDEX
_ak_update_us_daily throw ex: list index out of range, symbol = COZX
_ak_update_us_daily throw ex: 'date', symbol = DLHZ
_ak_update_us_daily throw ex: 'date', symbol = DXG

 73%|███████████████████████████████████████████████████████████████████████████████████                               | 11962/16415 [00:09<00:06, 720.06it/s]

_ak_update_us_daily throw ex: 'date', symbol = ELCG
_ak_update_us_daily throw ex: 'date', symbol = ELEP
_ak_update_us_daily throw ex: 'date', symbol = EMCH
_ak_update_us_daily throw ex: list index out of range, symbol = EUHY

 75%|█████████████████████████████████████████████████████████████████████████████████████▍                            | 12296/16415 [00:10<00:06, 630.07it/s]

_ak_update_us_daily throw ex: 'date', symbol = EVGNU
_ak_update_us_daily throw ex: 'date', symbol = FFFZ
_ak_update_us_daily throw ex: 'date', symbol = FGO
_ak_update_us_daily throw ex: 'date', symbol = FMSTU
_ak_update_us_daily throw ex: 'date', symbol = FP

 76%|███████████████████████████████████████████████████████████████████████████████████████                           | 12536/16415 [00:11<00:07, 546.58it/s]

_ak_update_us_daily throw ex: 'date', symbol = GDD
_ak_update_us_daily throw ex: list index out of range, symbol = GEMG
_ak_update_us_daily throw ex: 'date', symbol = GGL

 78%|█████████████████████████████████████████████████████████████████████████████████████████▏                        | 12840/16415 [00:12<00:07, 508.38it/s]

_ak_update_us_daily throw ex: 'date', symbol = GRDNU
_ak_update_us_daily throw ex: 'date', symbol = GTSG
_ak_update_us_daily throw ex: list index out of range, symbol = HOII
_ak_update_us_daily throw ex: 'date', symbol = HRLR

 79%|█████████████████████████████████████████████████████████████████████████████████████████▉                        | 12958/16415 [00:13<00:08, 411.86it/s]

_ak_update_us_daily throw ex: 'date', symbol = HUDA U
_ak_update_us_daily throw ex: 'date', symbol = HWEP

 80%|██████████████████████████████████████████████████████████████████████████████████████████▊                       | 13078/16415 [00:13<00:07, 420.15it/s]

_ak_update_us_daily throw ex: 'date', symbol = IGLEU

 80%|███████████████████████████████████████████████████████████████████████████████████████████▎                      | 13154/16415 [00:13<00:08, 365.84it/s]

_ak_update_us_daily throw ex: 'date', symbol = IGTA.UN

 83%|██████████████████████████████████████████████████████████████████████████████████████████████▏                   | 13562/16415 [00:14<00:05, 525.58it/s]

_ak_update_us_daily throw ex: 'date', symbol = JW
_ak_update_us_daily throw ex: 'date', symbol = LBRJ

 83%|██████████████████████████████████████████████████████████████████████████████████████████████▋                   | 13637/16415 [00:14<00:07, 376.94it/s]

_ak_update_us_daily throw ex: 'date', symbol = LCFYU
_ak_update_us_daily throw ex: 'date', symbol = LEWY

 84%|███████████████████████████████████████████████████████████████████████████████████████████████▎                  | 13727/16415 [00:15<00:06, 413.47it/s]

_ak_update_us_daily throw ex: 'date', symbol = LRTX
_ak_update_us_daily throw ex: list index out of range, symbol = MAAY

 85%|████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 13913/16415 [00:15<00:06, 371.82it/s]

_ak_update_us_daily throw ex: 'date', symbol = MDLS
_ak_update_us_daily throw ex: 'date', symbol = MFB

 85%|████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 13962/16415 [00:15<00:07, 309.87it/s]

_ak_update_us_daily throw ex: 'date', symbol = MKTR
_ak_update_us_daily throw ex: 'date', symbol = MMTX
_ak_update_us_daily throw ex: 'date', symbol = MNGO
_ak_update_us_daily throw ex: 'date', symbol = MOTA

 85%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                | 14001/16415 [00:16<00:13, 177.92it/s]

_ak_update_us_daily throw ex: 'date', symbol = MOTAW

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                | 14053/16415 [00:17<00:16, 146.90it/s]

_ak_update_us_daily throw ex: 'date', symbol = MRZM
_ak_update_us_daily throw ex: 'date', symbol = MTRS

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                | 14081/16415 [00:17<00:18, 124.49it/s]

_ak_update_us_daily throw ex: 'date', symbol = MVRK

 86%|██████████████████████████████████████████████████████████████████████████████████████████████████▍               | 14176/16415 [00:18<00:15, 147.56it/s]

_ak_update_us_daily throw ex: 'date', symbol = MXRX
_ak_update_us_daily throw ex: 'date', symbol = NFTX

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 14431/16415 [00:18<00:05, 357.13it/s]

_ak_update_us_daily throw ex: 'date', symbol = ONS.UN

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 14475/16415 [00:18<00:07, 273.05it/s]

_ak_update_us_daily throw ex: 'date', symbol = OPHV
_ak_update_us_daily throw ex: list index out of range, symbol = OSCG

 88%|████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 14509/16415 [00:19<00:07, 251.49it/s]

_ak_update_us_daily throw ex: 'date', symbol = PACI.U

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████             | 14550/16415 [00:19<00:09, 193.78it/s]

_ak_update_us_daily throw ex: 'date', symbol = PCCTW

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 14742/16415 [00:19<00:05, 295.78it/s]

_ak_update_us_daily throw ex: list index out of range, symbol = PMNV
_ak_update_us_daily throw ex: 'date', symbol = PTEST.X

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 14777/16415 [00:20<00:06, 249.95it/s]

_ak_update_us_daily throw ex: 'date', symbol = PTEST.Z

 91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████          | 15000/16415 [02:06<09:08,  2.58it/s]

_ak_update_us_daily throw ex: 'date', symbol = RHDM

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 15038/16415 [02:29<10:33,  2.17it/s]

_ak_update_us_daily throw ex: 'date', symbol = RNBW

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 15248/16415 [04:30<10:13,  1.90it/s]

_ak_update_us_daily throw ex: 'date', symbol = SFCH

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 15307/16415 [05:06<10:15,  1.80it/s]

_ak_update_us_daily throw ex: 'date', symbol = SJA

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 15380/16415 [05:45<08:28,  2.04it/s]

_ak_update_us_daily throw ex: 'date', symbol = SODR

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 15391/16415 [05:51<07:19,  2.33it/s]

_ak_update_us_daily throw ex: list index out of range, symbol = SOLM

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 15398/16415 [05:54<08:12,  2.07it/s]

_ak_update_us_daily throw ex: 'date', symbol = SOSH

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 15465/16415 [06:36<08:13,  1.93it/s]

_ak_update_us_daily throw ex: 'date', symbol = SQFL

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 15655/16415 [08:58<06:11,  2.05it/s]

_ak_update_us_daily throw ex: 'date', symbol = TENJ

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 15688/16415 [09:16<05:18,  2.28it/s]

_ak_update_us_daily throw ex: 'date', symbol = THNK

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 16023/16415 [12:43<03:36,  1.81it/s]

_ak_update_us_daily throw ex: 'date', symbol = VHCIU

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 16084/16415 [13:19<02:40,  2.07it/s]

_ak_update_us_daily throw ex: 'date', symbol = VTRO

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 16154/16415 [13:57<01:50,  2.37it/s]

_ak_update_us_daily throw ex: list index out of range, symbol = WMTI

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 16188/16415 [14:16<01:40,  2.25it/s]

_ak_update_us_daily throw ex: 'date', symbol = WXT

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 16246/16415 [14:51<02:01,  1.39it/s]

_ak_update_us_daily throw ex: 'date', symbol = XJET

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 16366/16415 [15:56<00:22,  2.22it/s]

_ak_update_us_daily throw ex: 'date', symbol = YXR

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 16399/16415 [16:15<00:07,  2.05it/s]

_ak_update_us_daily throw ex: 'date', symbol = ZRSP

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16415/16415 [16:22<00:00, 16.70it/s]

In [126]:
stock_us_daily_df = ak.stock_us_daily(symbol="AAPL", adjust="qfq-factor")

In [132]:
stock_us_daily_df['qfq_factor'] = stock_us_daily_df['qfq_factor'].astype(np.float64)
stock_us_daily_df['adjust'] = stock_us_daily_df['adjust'].astype(np.float64)

In [134]:
stock_us_daily_df

         date  qfq_factor    adjust
0  2025-08-11    1.000000  0.000000
1  2025-05-12    1.000000 -0.260000
2  2025-02-10    1.000000 -0.520000
3  2024-11-11    1.000000 -0.770000
4  2024-11-08    1.000000 -1.020000
..        ...         ...       ...
90 1987-11-17    0.008929 -9.679669
91 1987-08-10    0.008929 -9.679695
92 1987-06-16    0.008929 -9.679714
93 1987-05-11    0.004464 -9.679714
94 1900-01-01    0.004464 -9.679723

[95 rows x 3 columns]

## 3. tushare

- 单次最大8000行，可根据日期循环获取
- 单独付费，2000元/年

In [105]:
dc = DataCenter()

In [110]:
dc.pro.us_daily(ts_code='AAPL')

,ts_code,trade_date,close,open,high,low,pre_close,pct_change,vol,amount,vwap
0,AAPL,20251107,268.47,269.79,272.29,266.77,269.77,-0.48,48227364,1.297508e+10,269.04
1,AAPL,20251106,269.77,267.89,273.40,267.89,270.14,-0.14,51204047,1.386800e+10,270.84
2,AAPL,20251105,270.14,268.61,271.70,266.93,270.04,0.04,43683071,1.178450e+10,269.77
3,AAPL,20251104,270.04,268.32,271.49,267.62,269.05,0.37,49274848,1.329625e+10,269.84
4,AAPL,20251103,269.05,270.42,270.85,266.25,270.37,-0.49,50194583,1.345499e+10,268.06
...,...,...,...,...,...,...,...,...,...,...,...
7995,AAPL,19940202,33.00,33.25,33.25,32.50,33.25,-0.75,1307600,NaN,NaN
7996,AAPL,19940201,33.25,33.00,33.50,32.25,32.75,1.53,1399300,NaN,NaN
7997,AAPL,19940131,32.75,33.50,33.75,32.75,34.00,-3.68,2128400,NaN,NaN
7998,AAPL,19940128,34.00,34.25,34.75,33.75,34.13,-0.37,1218200,NaN,NaN
7999,AAPL,19940127,34.13,33.50,34.25,33.00,33.50,1.87,1180800,NaN,NaN

In [112]:
dc.pro.us_adjfactor(ts_code='AAPL')

Exception: 抱歉，您没有接口访问权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

In [44]:
spot_em = ak.stock_us_spot_em()

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [43]:
from massive import RESTClient

client = RESTClient("10uFpzT9vu7thJsykdIMrYalPPnxSn4_")

aggs = []
for a in client.list_aggs(
    "AAPL",
    1,
    "day",
    "2025-10-01",
    "2025-10-31",
    limit=50000,
):
    aggs.append(a)

print(aggs)

[Agg(open=255.04, high=258.79, low=254.93, close=255.45, volume=48713940.0, vwap=256.004, timestamp=1759291200000, transactions=535581, otc=None), Agg(open=256.575, high=258.18, low=254.15, close=257.13, volume=42630239.0, vwap=256.855, timestamp=1759377600000, transactions=485229, otc=None), Agg(open=254.665, high=259.24, low=253.95, close=258.02, volume=49155614.0, vwap=257.8596, timestamp=1759464000000, transactions=706052, otc=None), Agg(open=257.99, high=259.07, low=255.05, close=256.69, volume=44664118.0, vwap=256.8692, timestamp=1759723200000, transactions=649161, otc=None), Agg(open=256.805, high=257.4, low=255.43, close=256.48, volume=31955776.0, vwap=256.4092, timestamp=1759809600000, transactions=511382, otc=None), Agg(open=256.52, high=258.52, low=256.11, close=258.06, volume=36496895.0, vwap=257.8119, timestamp=1759896000000, transactions=395556, otc=None), Agg(open=257.805, high=258, low=253.14, close=254.04, volume=38322012.0, vwap=254.5102, timestamp=1759982400000, transactions=536585, otc=None), Agg(open=254.94, high=256.38, low=244, close=245.27, volume=61999098.0, vwap=248.3661, timestamp=1760068800000, transactions=908253, otc=None), Agg(open=249.38, high=249.69, low=245.56, close=247.66, volume=38142942.0, vwap=247.9036, timestamp=1760328000000, transactions=614923, otc=None), Agg(open=246.6, high=248.845, low=244.7, close=247.77, volume=35477986.0, vwap=247.3488, timestamp=1760414400000, transactions=533528, otc=None), Agg(open=249.485, high=251.82, low=247.47, close=249.34, volume=33893611.0, vwap=249.5813, timestamp=1760500800000, transactions=528880, otc=None), Agg(open=248.25, high=249.04, low=245.13, close=247.45, volume=39776974.0, vwap=247.354, timestamp=1760587200000, transactions=616258, otc=None), Agg(open=248.02, high=253.38, low=247.27, close=252.29, volume=49146961.0, vwap=250.7598, timestamp=1760673600000, transactions=634830, otc=None), Agg(open=255.885, high=264.375, low=255.63, close=262.24, volume=90483029.0, vwap=261.7003, timestamp=1760932800000, transactions=1160822, otc=None), Agg(open=261.88, high=265.29, low=261.83, close=262.77, volume=46695748.0, vwap=263.4176, timestamp=1761019200000, transactions=714945, otc=None), Agg(open=262.65, high=262.85, low=255.43, close=258.45, volume=45011970.0, vwap=258.6829, timestamp=1761105600000, transactions=687110, otc=None), Agg(open=259.94, high=260.62, low=258.0101, close=259.58, volume=32752139.0, vwap=259.577, timestamp=1761192000000, transactions=482428, otc=None), Agg(open=261.19, high=264.13, low=259.18, close=262.82, volume=38253517.0, vwap=262.539, timestamp=1761278400000, transactions=599532, otc=None), Agg(open=264.88, high=269.12, low=264.6501, close=268.81, volume=44888052.0, vwap=267.0053, timestamp=1761537600000, transactions=661981, otc=None), Agg(open=268.985, high=269.89, low=268.15, close=269, volume=41534547.0, vwap=268.9865, timestamp=1761624000000, transactions=585457, otc=None), Agg(open=269.275, high=271.41, low=267.11, close=269.7, volume=51086742.0, vwap=269.5125, timestamp=1761710400000, transactions=687375, otc=None), Agg(open=271.99, high=274.14, low=268.48, close=271.4, volume=69886281.0, vwap=272.2528, timestamp=1761796800000, transactions=984732, otc=None), Agg(open=276.99, high=277.32, low=269.16, close=270.37, volume=86167123.0, vwap=271.3276, timestamp=1761883200000, transactions=1013846, otc=None)]